#!/usr/bin/env bash
# Updates upstream unit-test expectations to Kyvernetria's intentional
# defaults (grace period, scheduler plugins, controllers, RBAC). Upstream test
# logic is not touched; only expected values change.
# Usage: hack/update-test-expectations.sh <kyvernetria-tree>
set -euo pipefail
tree="${1:?usage: $0 <kyvernetria-tree>}"
cd "${tree}"

add_import() { # file
  grep -q '"k8s.io/kubernetes/pkg/kyvernetria"' "$1" ||
    perl -0pi -e 's|(\nimport \(\n.*?)\n\)\n|$1\n\n\t"k8s.io/kubernetes/pkg/kyvernetria"\n)\n|s' "$1"
}

# Event TTL: 30 days instead of 1 hour.
for f in cmd/kube-apiserver/app/options/options_test.go pkg/controlplane/apiserver/options/options_test.go; do
  if grep -qE 'EventTTL: +1 \* time.Hour,' "$f"; then
    perl -pi -e 's|(EventTTL: +)1 \* time.Hour,|${1}kyvernetria.EventTTL,|' "$f"
    add_import "$f"
  fi
done

# Termination grace period: 300s instead of 30s.
perl -pi -e 's|(".Spec.TerminationGracePeriodSeconds": +)`30`,|$1`300`,|' pkg/apis/core/v1/defaults_test.go
for f in pkg/apis/apps/v1/defaults_test.go pkg/apis/apps/v1beta1/defaults_test.go \
         pkg/apis/apps/v1beta2/defaults_test.go pkg/apis/extensions/v1beta1/defaults_test.go; do
  if grep -q 'period := int64(v1.DefaultTerminationGracePeriodSeconds)' "$f"; then
    perl -pi -e 's|period := int64\(v1.DefaultTerminationGracePeriodSeconds\)|period := int64(kyvernetria.DefaultTerminationGracePeriodSeconds)|g' "$f"
    add_import "$f"
  fi
done

# Scheduler: PlaceMemory scores right after ImageLocality.
grep -q 'names.PlaceMemory' pkg/scheduler/apis/config/testing/defaults/defaults.go ||
  perl -pi -e 's|^(\t+)\{Name: names.ImageLocality, Weight: 1\},\n|$&$1\{Name: names.PlaceMemory, Weight: 2\},\n|' \
    pkg/scheduler/apis/config/testing/defaults/defaults.go
for f in pkg/scheduler/apis/config/v1/default_plugins_test.go pkg/scheduler/apis/config/v1/defaults_test.go; do
  grep -q 'names.PlaceMemory' "$f" ||
    perl -pi -e 's|^(\t+)\{Name: names.ImageLocality, Weight: ptr.To\[int32\]\(1\)\},\n|$&$1\{Name: names.PlaceMemory, Weight: ptr.To[int32](2)\},\n|' "$f"
done

# Controller manager: the Kyvernetria controllers are declared.
grep -q KyvernetriaWorryController cmd/kube-controller-manager/app/controllermanager_test.go ||
  perl -0pi -e 's|(\t\tnames.ServiceCIDRController,\n)|$1\t\tKyvernetriaPlaceMemoryController,\n\t\tKyvernetriaRelationshipsController,\n\t\tKyvernetriaWorryController,\n|' \
    cmd/kube-controller-manager/app/controllermanager_test.go

gofmt -w pkg/apis/apps pkg/apis/extensions cmd/kube-apiserver/app/options pkg/controlplane/apiserver/options

# RBAC fixtures are generated by the upstream test itself.
UPDATE_BOOTSTRAP_POLICY_FIXTURE_DATA=true go test ./plugin/pkg/auth/authorizer/rbac/bootstrappolicy/ >/dev/null 2>&1 || true
echo "test expectations updated in ${tree}"
